const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { getDBconn }= require('../config/dbConfig');
const { remoteMongoDb } = getDBconn();

const bulkFoodOrder = new Schema({
    orderNo: Number,
    customerId: { type: Schema.Types.ObjectId, required: true },
    customerName: String,
    customerLocation: {
        tagLocation: String,
        geolocation: { lat: Number, lng: Number },
        address: String,
        location: String,
        landmark: String,
        pincode: Number,
        city:String,
        state: String
    },
    orderTransferred: Boolean,
    transferExtraAmt: Number,
    reduceExtraAmt: Number,
    transferHistory: [{ kitchenName: String, kitchenPhoneNo: String }],
    distance: Number,
    kitchenId: { type: Schema.Types.ObjectId },
    kitchenName: String,
    kitchenPhoneNo: String,
    kitchenmapTelNo:{type: String},
    kitchenAddress: {
        address1: String,
        address2: String,
        landmark: String,
    },
    kitchenGeolocation: { lat: Number, lng: Number },
    customerPhoneNo: { type: String, required: true },
    customerEmail: { type: String },
    orderstatus: {
        type: String, enum: ['paymentInitiated', 'paymentInprogress', 'paymentFailed', 'deliveryBoyAssigned', 'handedOverToDeliveryBoy',
            'onTheWay', 'placed', 'readyForDelivery', 'accepted', 'inprogress', 'cancelled', 'delivered', 'preparing']
    },
    orderType: { type: String, enum: ['bulkMeals', 'individualMeals', 'bulkSnacks', 'individualSnacks', 'predefinedSnackbox', 'customSnackbox', 'apartmentBulk'] },
    taxes: Number,
    platformChargesTax: Number,
    deliveryChargesTax: Number,
    deliveryCharges: Number,
    itemTotalTax: Number,
    packagingChargesTax: Number,
    itemAmount: Number,
    bulkItemAmount: Number,
    amount: Number,
    amtPaidToKitchen: Boolean,
    skipCommission: Boolean,
    startManualDelivery: Boolean,
    amtAfterCommisionPaidToKitchen: Number,
    stopPaymentValidation: Boolean,
    beforePackingImageUrl: String,
    afterPackingImageUrl: String,
    payment_id: String,
    order_id: String,
    receipt: String,
    itemList: [{
        itemName: String,
        imageUrl: String,
        count: Number,
        itemPrice: Number,
        itemType: String,
        itemDescription: String,
        itemServingType: String,
        servingQuantity: Number,
        servingQuantityUnit: String,
        packagingCost: Number,
        packagingDescription: String,
    }],
    addOns: [{
        addOnName: String,
        imageUrl: String,
        count: Number,
        addOnPrice: Number,
        addOnType: String,
        hidetoKitchen: Boolean
    }],
    statusHistory: [{
        orderstatus: String,
        updatedOn: Date,
        updatedBy: String,
        updateByType: String
    }],
    orderCreatedBy: {type: String,
        enum: ['navmool_web', 'mealawe_app_ios', 'mealawe_app_android', 'mealawe_web','User', 'Admin', 'Auto', 'Web'],default: 'User'},
    specialRequest: String,
    orderDate: Date,
    deliveryDate: Date,
    slotStartTime: Date,
    deliveryTaskId: String,
    slotEndTime: Date,
    deliveryAmtPaidByMealawe: Number,
    deliveryVendor: { type: String, enum: ['Dunzo', 'Porter', 'ShadowFax', 'Pidge'] },
    deliveryTrackURL: String,
    deliveryCost: Number,
    voucherCode: String,
    couponCode:String,
    voucherDiscount: Number,
    packagingCost: Number,
    discount: Number,
    packagingCostByUser: Number,
    firstKitchenName: String,
    clusterId: String,
    clusterName: String,
    moneyWalletPointsUsed: Number,
    mealaweWalletPointsUsed: Number,
    pgName: String,
    transactionTime: Date,
   totalEcoFriendlyPackagingCharges: Number,
   totalEcoFriendlyPackagingChargesDiscount: Number,
   finalBulkDelCharges: Number,
   finalBulkDelDiscount: Number,
   finalBulkPlatformCharges: Number, 
   finalBulkPlatformDiscount: Number, 
   deliveryInstructions: String,
   flatNumber: String,
   roomNumber: String,
   wingName: String,
   updateByType: String,
   updatedBy: String, 
   pgName: String,
   transactionTime: Date,
   apartmentOtp: String,
   apartmentId: { type: Schema.Types.ObjectId },
   apartmentName: String,
   enableDelivery: { type: Boolean, default: true },
   enableSelfPickup: { type: Boolean, default: false },
   runner: {
       name: String,
       phone_number: String,
       location: {
           lat: { type: Number },
           lng: { type: Number }
       }
   },
});

module.exports = remoteMongoDb.model('bulkFoodOrder', bulkFoodOrder);