const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { getDBconn } = require('../config/dbConfig');
const { remoteMongoDb } = getDBconn();

const foodOrder = new Schema({
    orderNo: Number,
    customerId: { type: Schema.Types.ObjectId, required: true },
    customerName: String,
    customerLocation: {
        tagLocation: String,
        geolocation: { lat: Number, lng: Number },
        address: String,
        location: String,
        landmark: String,
        pincode: Number,
        city:String,
        state: String
    },
    customerPhoneNo: { type: String, required: true },
    customerEmail: { type: String },
    firstKitchenName: String,
    kitchenId: { type: Schema.Types.ObjectId, required: true },
    kitchenName: String,
    kitchenPhoneNo: String,
    kitchenmapTelNo: String ,
    kitchenAddress: {
        address1: String,
        address2: String,
        landmark: String,
        pincode: Number,
    },
    kitchenGeolocation: { lat: Number, lng: Number },
    orderType: { type: String, enum: ['advance', 'daily', 'allDay', 'subscription', 'oyo','apartment_today','apartment_advance'] },
    mealType: { type: String, enum: ['Breakfast', 'Lunch', 'HighTea', 'Dinner'] },
    orderDate: Date,
    orderComplitionDate: Date,
    orderComplitionTime: Date,
    itemAmount: Number,
    amount: Number,
    deliveryCharges: Number,
    taxes: Number,
    discount: Number,
    kitchenDiscount: Number,
    orderstatus: {
        type: String,
        enum: ['paymentInitiated', 'paymentInprogress', 'paymentFailed', 'placed', 'accepted', 'cancelledByUser',
            'cancelledByKitchen', 'rejectedByKitchen', 'preparing',
            'readyToDelivery', 'deliveryBoyAssigned', 'handedOverToDeliveryBoy',
            'onTheWay', 'delivered', 'autoCancelled', 'refundCompleted']
    },
    deliveryTaskId: String,
    itemList: [{
        itemName: String,
        imageUrl: String,
        count: Number,
        itemPrice: Number,
        itemType: String,
        itemDescription: String,
        itemIsCombo: Boolean,
        itemIsBreakfast: Boolean,
        mealawePrice: Number,
        itemServingType: String,
        servingQuantity: Number,
        servingQuantityUnit: String,
        itemServingDate: String,
    }],
    addOns: [{
        addOnName: String,
        imageUrl: String,
        count: Number,
        addOnPrice: Number,
        addOnType: String,
        mealawePrice: Number,
        hidetoKitchen: Boolean
    }],
    specialRequest: String,
    nonContactDelivery: Boolean,
    feedbackProvided: Boolean,
    payment_id: String,
    order_id: String,
    receipt: String,
    refund_id: String,
    refund_status: String,
    refund_amount: Number,
    cancel_comment: String,
    couponCode: String,
    amtPaidToKitchen: Boolean,
    skipCommission: Boolean,
    amtAfterCommisionPaidToKitchen: Number,
    orderCommission: Number,
    moneyWalletPointsUsed: Number,
    mealaweWalletPointsUsed: Number,
    distance: Number,
    statusHistory: [{
        orderstatus: String,
        updatedOn: Date,
        updatedBy: String,
        updateByType: String
    }],
    orderTransferred: Boolean,
    transferExtraAmt: Number,
    reduceExtraAmt: Number,
    transferHistory: [{ kitchenName: String, kitchenPhoneNo: String, updatedBy: String, updateByType: String }],
    stopRefundProcess: Boolean,
    subscriptionMasterId: { type: Schema.Types.ObjectId },
    subscriptionMasterOrderId: String,
    subscriptionChildId: String,
    subscriptionSlot: String,
    mealaweDeliveryDiscount: Number,
    mealaweItemDiscount: Number,
    mealaweTotalAmt: Number,
    mealaweKitchenDiscount: Number,
    voucherCode: String,
    voucherDiscount: Number,
    couponCode: String,
    couponDiscount: Number,
    extraDiscount: Number,
    slotStartTime: Date,
    slotEndTime: Date,
    startManualDelivery: Boolean,
    dailyOrderDeliveryTime: Date,
    orderIsTrialMeal: Boolean,
    deliveryVendor: String,
    beforePackingImageUrl: String,
    afterPackingImageUrl: String,
    orderCreatedBy: {type: String,
        enum: ['navmool_web', 'mealawe_app_ios', 'mealawe_app_android', 'mealawe_web','User', 'Admin', 'Auto', 'Web']},
    stopPaymentValidation: Boolean,
    subscriptionLunchSlot: String,
    subscriptionDinnerSlot: String,
    subscriptionBreakfastSlot: String,
    deliveryAmtPaidByMealawe: Number,
    packageName: String,
    packageCategory: String,
    packageSubCategory: String,
    payToKitchenPerMealWithAddon: Number,
    payToKitchenPerMealWithAddon2: Number,
    pickup_otp: String,
    drop_otp: String,
    deliveryTrackURL: String,
    selfDeliveryCreated: Boolean,
    dontSendCutlery: Boolean,
    platformCharges: Number,
    platformChargesDiscount: Number,
    cutleryDiscount: Number,
    subscriptionDeliveryCharges: Number,
    subscriptionDeliveryDiscount: Number,
    ecoFriendlyPackagingCharges: Number,
    foodOrderType: String,
    isTrial: Boolean,
    cgst: Number,
    sgst: Number,
    deliveryChargesGST: Number,
    packagingChargesGST: Number,
    platformChargesGST: Number,
    treePlantationOpted: Boolean,
    treePlantationDone: Boolean,
    treePlantationAmount: Number,
    treePlantationDiscount: Number,
    treeReceiverName: String,
    deliveryByMealaweBoy: Boolean,
    skipWalletPayment: Boolean,
    clusterId: String,
    clusterName: String,
    deliveryPartnerInstruction: [{ instruction: String, selected: Boolean, addonIconType: String }],
    specialInstruction: [{ instruction: String, selected: Boolean }],
    routeNo: Number,
    routeRank: Number,
    handOverTo: String,
    rmInfo: {
        rmId: String,
        rmName: String
    },
    pgName: String,
    transactionTime: Date,
    enableDelivery: { type: Boolean, default: true },
    apartmentOtp: String,
  apartmentId: { type: Schema.Types.ObjectId },
  apartmentName: String,
  wingName: String,
  roomNumber: String,
  enableSelfPickup: { type: Boolean, default: true }, // NEW: Self pickup enabled by default
  runner: {
      name: String,
      phone_number: String,
      location: {
          lat: { type: Number },
          lng: { type: Number }
      }
  },
  tripId: String,
  startKM: Number,
  selfieImageUrl: String,
  selfieGps: {
      lat: { type: Number },
      lng: { type: Number }
  },
  selfieCapturedAt: Date,
  odometerImageUrl: String,
  odometerCapturedAt: Date,
  riderTripStartedAt: Date,
  proofImageUrl: String,
  proofCapturedAt: Date,
  proofGps: {
      lat: { type: Number },
      lng: { type: Number }
  }


});
module.exports = remoteMongoDb.model('FoodOrder', foodOrder);
