const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { getDBconn }= require('../config/dbConfig');
const { remoteMongoDb } = getDBconn();

const foodOrderSubscription = new Schema({
    orderNo: String,
    customerId: { type: Schema.Types.ObjectId, required: true },
    customerName: String,
    customerLocation: {
        tagLocation: String,
        geolocation: { lat: Number, lng: Number },
        address: String,
        location: String,
        landmark: String
    },
    customerPhoneNo: { type: String, required: true },
    customerEmail: { type: String },
    kitchenId: { type: Schema.Types.ObjectId, required: true },
    kitchenName: String,
    kitchenPhoneNo: String,
    kitchenAddress: {
        address1: String,
        address2: String,
        landmark: String,
    },
    kitchenGeolocation: { lat: Number, lng: Number },
    orderType: { type: String, enum: ['subscriptionParent'] },
    orderDate: Date,
    itemAmount: Number,
    amount: Number,
    deliveryCharges: Number,
    taxes: Number,
    discount: Number,
    kitchenDiscount: Number,
    orderstatus: {
        type: String,
        enum: ['paymentInitiated', 'paymentInprogress', 'paymentFailed', 'placed', 'accepted', 'cancelledByUser',
            'cancelledByKitchen', 'autoCancelled', 'refundCompleted']
    },
    itemList: [{
        itemName: String,
        count: Number,
        itemPrice: Number,
        itemType: String,
        itemDescription: String,
        itemIsCombo: Boolean,
        itemIsBreakfast: Boolean,
        mealawePrice: Number,
        itemServingType: String,
        servingQuantity: Number,
        servingQuantityUnit: String,
    }],
    addOns: [{
        addOnName: String,
        count: Number,
        addOnPrice: Number,
        addOnType: String,
        mealawePrice: Number,
        hidetoKitchen: Boolean
    }],
    specialRequest: String,
    nonContactDelivery: Boolean,
    feedbackProvided: Boolean,
    payment_id: String,
    order_id: String,
    receipt: String,
    refund_id: String,
    refund_status: String,
    refund_amount: Number,
    cancel_comment: String,
    couponCode: String,
    skipCommission: Boolean,
    moneyWalletPointsUsed: Number,
    mealaweWalletPointsUsed: Number,
    distance: Number,
    statusHistory: [{
        orderstatus: String,
        updatedOn: Date,
        updatedBy: String,
        updateByType: String
    }],
    stopRefundProcess: Boolean,
    orderTransferred: Boolean,
    transferHistory: [{ kitchenName: String, kitchenPhoneNo: String }],
    subscriptionDays: Number,
    subscriptionStartDate: Date,
    mealTime: String,
    subscriptionSlot: String,
    dailyOrderList: [{
        foodOrderId: { type: Schema.Types.ObjectId },
        orderNo: Number,
        mealTime: { type: String, enum: ['Breakfast', 'Lunch', 'Dinner'] },
        subscriptionSlot: String,
        orderDate: Date,
        itemAmount: Number,
        amount: Number,
        deliveryCharges: Number,
        taxes: Number,
        discount: Number,
        kitchenDiscount: Number,
        moneyWalletPointsUsed: Number,
        mealaweWalletPointsUsed: Number,
        specialRequest: String,
        nonContactDelivery: Boolean,
        mealaweDeliveryDiscount: Number,
        mealaweItemDiscount: Number,
        mealaweTotalAmt: Number,
        mealaweKitchenDiscount: Number,
        couponCode: String,
        voucherCode: String,
        voucherDiscount: Number,
        extraDiscount: Number
    }],
    mealaweDeliveryDiscount: Number,
    mealaweItemDiscount: Number,
    mealaweTotalAmt: Number,
    mealaweKitchenDiscount: Number,
    voucherCode: String,
    voucherDiscount: Number,
    extraDiscount: Number,
    orderCreatedBy: {type: String,
        enum: ['navmool_web', 'mealawe_app_ios', 'mealawe_app_android', 'mealawe_web','User', 'Admin', 'Auto', 'Web']},
    deliveryVendor: { type: String, enum: ['Dunzo', 'Porter', 'ShadowFax', 'Pidge'] },
    clusterId: String,
    clusterName: String
});
module.exports = remoteMongoDb.model('FoodOrderSubscription', foodOrderSubscription);
