const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { getDBconn } = require('../config/dbConfig');
const { remoteMongoDb } = getDBconn();

const foodOrderPackage = new Schema({
    orderNo: String,
    customerId: { type: Schema.Types.ObjectId, required: true },
    customerName: String,
    customerLocation: {
        tagLocation: String,
        geolocation: { lat: Number, lng: Number },
        address: String,
        location: String,
        landmark: String,
        pincode: Number,
        city:String,
    },
    customerPhoneNo: { type: String, required: true },
    customerEmail: { type: String },
    orderType: { type: String, enum: ['subscriptionPackage'] },
    kitchenId: { type: Schema.Types.ObjectId },
    kitchenName: String,
    kitchenPhoneNo: String,
    kitchenAddress: {
        address1: String,
        address2: String,
        landmark: String,
    },
    kitchenGeolocation: { lat: Number, lng: Number },
    distance: Number,
    orderDate: Date,
    itemAmount: Number,
    amount: Number,
    mealaweTotalAmt: Number,
    discount: Number,
    orderstatus: {
        type: String,
        enum: ['paymentInitiated', 'paymentInprogress', 'paymentFailed', 'placed', 'accepted', 'cancelledByUser',
            'cancelledByKitchen', 'autoCancelled', 'refundCompleted']
    },
    mealPackage: {
        packageName: String,
        packagePrice: Number,
        packageCategory: String,
        packageSubCategory: String,
        packageType: String,
        days: Number,
        payToKitchenPerMeal: Number,
        payToKitchenPerMeal2: Number,
        vegMealDescription: String,
        nonVegMealDescription: String,
        deliveryOnWeekends: Boolean,
        count: Number,
        discount: Number,
        userAmount: Number,
        multiDateAllowed: Boolean,
        userSelectedDates: [{ type: String }],
        addonsList: [{
            addonName: String,
            extraPrice: Number,
            selected: Boolean,
            payKitchenExtraPerMeal: Number,
            day: Number,
            addOnType: String,
            daily: Boolean,
            userAmount: Number,
            dayText: String,
            dayCount: Number,
            hidetoKitchen: Boolean
        }],
        menuList: [{
            day: String,
            dayText: String,
            description: String,
            menuType: { type: String, enum: ['Veg', 'NonVeg'] }
        }]
    },
    mealTimeLunch: Boolean,
    mealTimeDinner: Boolean,
    mealTimeBreakfast: Boolean,
    specialRequest: String,
    payment_id: String,
    order_id: String,
    receipt: String,
    refund_id: String,
    refund_status: String,
    refund_amount: Number,
    cancel_comment: String,
    moneyWalletPointsUsed: Number,
    mealaweWalletPointsUsed: Number,
    distance: Number,
    statusHistory: [{
        orderstatus: String,
        updatedOn: Date,
        updatedBy: String,
        updateByType: String
    }],
    stopRefundProcess: Boolean,
    orderTransferred: Boolean,
    transferHistory: [{ kitchenName: String, kitchenPhoneNo: String, updatedBy: String, updateByType: String }],
    subscriptionDays: Number,
    subscriptionStartDate: Date,
    userSelectedDates: [{ type: String }],
    deliveryPartnerInstruction: [{ instruction: String, selected: Boolean, addonIconType: String }],
    multiDateAllowed: Boolean,
    taxes: Number,
    voucherCode: String,
    voucherDiscount: Number,
    dailyOrderList: [{
        foodOrderId: { type: Schema.Types.ObjectId },
        orderNo: Number,
        mealType: { type: String, enum: ['Breakfast', 'Lunch', 'Dinner'] },
        subscriptionSlot: String,
        orderDate: Date,
        orderstatus: String,
        itemAmount: Number,
        amount: Number,
        deliveryCharges: Number,
        ecoFriendlyPackagingCharges: Number,
        taxes: Number,
        discount: Number,
        kitchenDiscount: Number,
        moneyWalletPointsUsed: Number,
        mealaweWalletPointsUsed: Number,
        specialRequest: String,
        nonContactDelivery: Boolean,
        skipCommission: Boolean,
        mealaweDeliveryDiscount: Number,
        mealaweItemDiscount: Number,
        mealaweTotalAmt: Number,
        mealaweKitchenDiscount: Number,
        couponCode: String,
        voucherCode: String,
        voucherDiscount: Number,
        extraDiscount: Number,
        itemList: [{
            itemName: String,
            count: Number,
            itemPrice: Number,
            itemType: String,
            itemDescription: String,
            itemIsCombo: Boolean,
            mealawePrice: Number
        }],
        addOns: [{
            addOnName: String,
            count: Number,
            addOnPrice: Number,
            addOnType: String,
            mealawePrice: Number,
            hidetoKitchen: Boolean
        }],
    }],
    deliveryVendor: { type: String, enum: ['Dunzo', 'Porter', 'ShadowFax', 'Pidge'] },
    orderCreatedBy: {type: String,
        enum: ['navmool_web', 'mealawe_app_ios', 'mealawe_app_android', 'mealawe_web','User', 'Admin', 'Auto', 'Web']},
    wooCommerceId: Number,
    stopPaymentValidation: Boolean,
    subscriptionLunchSlot: String,
    subscriptionDinnerSlot: String,
    subscriptionBreakfastSlot: String,
    dontSendCutlery: Boolean,
    subscriptionDeliveryCharges: Number,
    subscriptionDeliveryChargesDiscount:Number,
    subscriptionDeleveryChargeGST:Number,
    ecoFriendlyPackagingChargesDiscount:Number,
    ecoFriendlyPackagingCharges: Number,
    subscriptionPackagingChargeGST:Number,
    platformCharges: Number,
    platformChargesDiscount:Number,
    subscriptionPlatformChargeGST:Number,
    cutleryDiscount: Number,
    subscriptionType: String,
    couponCode: String,
    couponDiscount: Number,
    cgst: Number,
    sgst: Number,
    treePlantationOpted: Boolean,
    treePlantationDone: Boolean,
    treePlantationAmount: Number,
    treePlantationDiscount: Number,
    treeReceiverName: String,
    deliveryByMealaweBoy: Boolean,
    skipWalletPayment: Boolean,
    clusterId: String,
    clusterName: String,
    specialInstruction: [{ instruction: String, selected: Boolean }],
    routeNo: Number,
    routeRank: Number,
    LunchrouteNo: Number,
    LunchrouteRank: Number,
    DinnerrouteNo: Number,
    DinnerrouteRank: Number,
    rmInfo: {
        rmId: String,
        rmName: String
    },
    pgName: String,
    transactionTime: Date
});
module.exports = remoteMongoDb.model('FoodOrderPackage', foodOrderPackage);
